In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from typing import Sequence
import pandas as pd
import numpy as np
sequences = {}

In [ ]:
df_loading = pd.read_csv('./drive/MyDrive/vtb24_hktn/loadings.csv', index_col='dateTime')

<ipython-input-55-e6ee252b2f34>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_loading = pd.read_csv('./drive/MyDrive/vtb24_hktn/loadings.csv', index_col='dateTime')


In [ ]:
df_loading = df_loading[df_loading['salePointName'] != float("nan")]

In [ ]:
del sequences[list(sequences)[274]]

In [ ]:
df_loading.groupby(['salePointName']).count()

Unnamed: 0  status  \
salePointName                                                           
ДО «Авиамоторный» Филиала № 7701 Банка ВТБ (ПАО)          797     797   
ДО «Автозаводский» Филиала № 7701 Банка ВТБ (ПАО)         797     797   
ДО «Академический» Филиала № 7701 Банка ВТБ (ПАО)         797     797   
ДО «Алексеевский» Филиала № 7701 Банка ВТБ (ПАО)          797     797   
ДО «Алтуфьево» Филиала № 7701 Банка ВТБ (ПАО)             797     797   
...                                                       ...     ...   
ДО №5 Банка ВТБ (ПАО)                                     797     797   
Филиал «Центральный» Банка ВТБ (ПАО)                      797     797   
Филиал Банка ВТБ (ПАО) в г. Москве                        797     797   
Филиал № 7701 Банка ВТБ (ПАО)                             797     797   
Филиал № 7777 Банка ВТБ (ПАО)                             797     797   

                                                   clients  employers  
salePointName                                                          
ДО «Авиамоторный» Филиала № 7701 Банка ВТБ (ПАО)       797        797  
ДО «Автозаводский» Филиала № 7701 Банка ВТБ (ПАО)      797        797  
ДО «Академический» Филиала № 7701 Банка ВТБ (ПАО)      797        797  
ДО «Алексеевский» Филиала № 7701 Банка ВТБ (ПАО)       797        797  
ДО «Алтуфьево» Филиала № 7701 Банка ВТБ (ПАО)          797        797  
...                                                    ...        ...  
ДО №5 Банка ВТБ (ПАО)                                  797        797  
Филиал «Центральный» Банка ВТБ (ПАО)                   797        797  
Филиал Банка ВТБ (ПАО) в г. Москве                     797        797  
Филиал № 7701 Банка ВТБ (ПАО)                          797        797  
Филиал № 7777 Банка ВТБ (ПАО)                          797        797  

[274 rows x 4 columns]

In [ ]:
from numpy.core.multiarray import array
for office in df_loading['salePointName'].unique():
  sequences[office] = array(df_loading[df_loading['salePointName'] == office]['clients']).astype(int)

In [ ]:
from numpy import hstack
for office in sequences:
  sequences[office] = sequences[office].reshape((len(sequences[office]),1))

In [ ]:
dataset = hstack(list([sequences[i] for i in sequences]))

In [ ]:
df_loading.values

array([[0, 'ДО «Солнечногорский» Филиала № 7701 Банка ВТБ (ПАО)', True,
        11.0, 9.0],
       [1, 'ДО «На Баранова» Филиала № 7701 Банка ВТБ (ПАО)', True, 23.0,
        18.0],
       [2, 'ДО «Лобня» Филиала № 7701 Банка ВТБ (ПАО)', True, 25.0, 21.0],
       ...,
       [220755,
        'ДО «Московский» в г. Московском Филиала № 7701 Банка ВТБ (ПАО)',
        True, 22.0, 20.0],
       [220756, 'ДО «Бронницкий» Филиала № 7701 Банка ВТБ (ПАО)', True,
        23.0, 20.0],
       [220758, nan, nan, nan, nan]], dtype=object)

In [169]:
def create_dataset(dataset, n_steps, n_out):
  X, y = list(), list()
  for i in range(len(dataset)):
    seq_end = i + n_steps
    if seq_end + n_out > len(dataset):
      break
    seq_x, seq_y=dataset[i:seq_end, 0], dataset[seq_end:seq_end + n_out,0]
    seq_x = seq_x.reshape((len(seq_x), 1))
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

In [170]:
X, y = create_dataset(dataset, 72, 72)

In [243]:
X.shape

(654, 72, 1)

In [244]:
verbose, epochs, batch_size = 0, 20, 16
n_timesteps, n_features, n_outputs = X.shape[1], X.shape[2], y.shape[1]

In [187]:
X

array([[[11],
        [ 9],
        [ 9],
        ...,
        [11],
        [11],
        [11]],

       [[ 9],
        [ 9],
        [ 9],
        ...,
        [11],
        [11],
        [ 9]],

       [[ 9],
        [ 9],
        [ 9],
        ...,
        [11],
        [ 9],
        [ 9]],

       ...,

       [[ 9],
        [ 9],
        [ 9],
        ...,
        [ 9],
        [ 9],
        [ 9]],

       [[ 9],
        [ 9],
        [ 9],
        ...,
        [ 9],
        [ 9],
        [ 9]],

       [[ 9],
        [ 9],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]]])

In [208]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import LSTM
from keras.layers import RepeatVector
from keras.layers import TimeDistributed

ModuleNotFoundError: ignored

In [189]:
# n_length = 72
# model = Sequential()
# model.add(LSTM(50, activation='relu', input_shape=(n_timesteps, n_features)))
# model.add(Dense(1))
# model.compile(optimizer='adam', loss='mse')
# # fit model
# model.fit(X, y, epochs=20, verbose=0)

In [245]:
model = Sequential()
model.add(LSTM(200, activation='relu', input_shape=(n_timesteps, n_features)))
model.add(RepeatVector(n_outputs))
model.add(LSTM(200, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(100, activation='relu')))
model.add(TimeDistributed(Dense(1)))
model.compile(loss='mse', optimizer='adam')
# fit network
model.fit(X, y, epochs=epochs, batch_size=batch_size, verbose=verbose)

In [246]:
import pickle
with open('./drive/MyDrive/vtb24_hktn/model.pkl', 'wb') as f:
  pickle.dump(model, f)

In [ ]:
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_timesteps, n_features))
yhat = model.predict(x_input, verbose=0)

In [255]:
def forecast(model, history, n_input):
	# flatten data
	data = array(history)
	# data = data.reshape((data.shape[0]*data.shape[1], data.shape[2]))
	# retrieve last observations for input data
	input_x = data[-n_input:, :]
	# reshape into [1, n_input, n]
	input_x = input_x.reshape((input_x.shape[1], input_x.shape[0], 1))
	# forecast the next week
	yhat = model.predict(input_x, verbose=0)
	# we only want the vector forecast
	yhat = yhat[0]
	return yhat

In [238]:
x_input = array([[  70,75,145],[80,85,165],[90,95,185]])
x_input = x_input.reshape((1, 3, 3))
x_input

array([[[ 70,  75, 145],
        [ 80,  85, 165],
        [ 90,  95, 185]]])

In [256]:
forecast(model, dataset, 72)
# dataset[-72:, 0].reshape((1, len(dataset[-72:, 0]), 1))
# dataset[-72:, :].shape

array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
      